otel:
  instrumentation:
    logback-appender:
      experimental:
        capture-code-attributes: true
  propagators:
    - b3
  resource:
    attributes:
      attributeFromYaml: true # boolean will be automatically converted to string by spring

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
    listener:
      idle-between-polls: 1000
    producer:
      transaction-id-prefix: test-
