version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/conventions"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/dependencyManagement"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/examples"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/gradle-plugins"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/smoke-tests"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    # need to scope gradle dependency updates down in this repo because most of the instrumentations
    # intentionally test against old library versions
    directory: "/.github/dependabot-symlinks"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/"
    allow:
      - dependency-name: "com.gradle*"
    registries:
      - gradle-plugin-portal
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
