max_retries = 6
max-concurrency = 4
cache = true
no_progress = true

# Stealth
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"

# Check links inside `<code>` and `<pre>` blocks and Markdown code blocks
include_verbatim = true

# Check fragments in links
include_fragments = true

# excluding links to pull requests and issues is done for performance
# stackexchange link fails with 403 when accessed by lychee
exclude = [
  '^https://github.com/open-telemetry/opentelemetry-java-instrumentation/(issues|pull)/\d+$',
  '^http://code.google.com/p/concurrentlinkedhashmap$',
  '^https://softwareengineering.stackexchange.com/questions/29727.*',
  '^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/io/opentelemetry/$',
  '^http://localhost:4318/.*',
]


