# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# and https://github.com/DavidAnson/markdownlint-cli2

# Configuration for markdownlint rules
config:
  # Default state for all rules
  default: true

  ul-style: false
  line-length: false
  no-duplicate-header:
    siblings_only: true
  ol-prefix:
    style: ordered
  no-inline-html: false
  fenced-code-language: false

# Globs to ignore (in addition to .gitignore)
ignores:
  - "**/build/**"
  - "CHANGELOG.md"
  - "licenses/licenses.md"
