otel:
  # "file_format" serves as opt-in to the new file format
  file_format: "1.0-rc.1"

  tracer_provider:
    processors:
      - batch:
          exporter:
            otlp_http:
              endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces # to test that we can use env vars in declarative config

  # very lightweight test to make sure the declarative config is loaded
  # the full config is tested in smoke-tests-otel-starter/spring-boot-2/src/testDeclarativeConfig
  instrumentation/development:
    java:
      foo:
        bar: baz
