name: Auto license report
on:
  push:
    branches:
      - 'renovate/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          cache-read-only: true

      - name: Update license report
        run: ./gradlew generateLicenseReport --no-build-cache

      - id: create-patch
        name: Create patch file
        run: |
          git add -N --ignore-removal licenses
          git diff > patch
          if [ -s patch ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload patch file
        if: steps.create-patch.outputs.exists == 'true'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: patch
          name: patch

  # separate job is just to isolate the OTELBOT_JAVA_INSTRUMENTATION_PRIVATE_KEY usage a bit
  apply:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download patch
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          path: ${{ runner.temp }}

      - id: check-patch
        name: Check patch
        working-directory: ${{ runner.temp }}
        run: |
          if [ -f patch ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        if: steps.check-patch.outputs.exists == 'true'
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_JAVA_INSTRUMENTATION_APP_ID }}
          private-key: ${{ secrets.OTELBOT_JAVA_INSTRUMENTATION_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: steps.check-patch.outputs.exists == 'true'
        with:
          token: ${{ steps.otelbot-token.outputs.token }}

      - name: Use CLA approved bot
        if: steps.check-patch.outputs.exists == 'true'
        run: .github/scripts/use-cla-approved-bot.sh

      - name: Apply patch and push
        if: steps.check-patch.outputs.exists == 'true'
        run: |
          git apply "${{ runner.temp }}/patch"
          git add licenses
          git commit -m "Update license report"
          git push
