name: Auto license report
on:
  push:
    branches:
      - 'renovate/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  auto-license-report:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-read-only: true

      - name: Use CLA approved bot
        run: .github/scripts/use-cla-approved-bot.sh

      - name: Update license report
        run: ./gradlew generateLicenseReport --no-build-cache

      - name: Commit and push if there are changes
        run: |
          git add licenses
          if ! git diff --cached --quiet; then
            git commit -m "Update license report"
            git push
          fi
