name: Build (daily --no-build-cache)

on:
  schedule:
    # daily at 4:48 UTC
    - cron: "48 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    with:
      no-build-cache: true
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      FLAKY_TEST_REPORTER_ACCESS_KEY: ${{ secrets.FLAKY_TEST_REPORTER_ACCESS_KEY }}

  test-latest-deps:
    uses: ./.github/workflows/reusable-test-latest-deps.yml
    with:
      no-build-cache: true
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      FLAKY_TEST_REPORTER_ACCESS_KEY: ${{ secrets.FLAKY_TEST_REPORTER_ACCESS_KEY }}

  # muzzle is not included here because it doesn't use gradle cache anyway and so is already covered
  # by the normal daily build

  # link-check is not included here because it doesn't use gradle cache anyway and so is already
  # covered by the normal daily build

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - common
      - test-latest-deps
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: >-
        ${{
          needs.common.result == 'success' &&
          needs.test-latest-deps.result == 'success'
        }}
