name: Build Spring Boot smoke test distribution

on:
  push:
    paths:
      - 'smoke-tests/springboot/**'
      - '.github/workflows/build-springboot-smoke-dist.yaml'
    branches: 'master'
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: springboot-smoke

      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin

      - name: Build Docker Image
        run: |
          ./gradlew jib -PtargetJDK=8 -Djib.httpTimeout=120000 -Djib.console=plain --stacktrace
          ./gradlew jib -PtargetJDK=11 -Djib.httpTimeout=120000 -Djib.console=plain --stacktrace
          ./gradlew jib -PtargetJDK=14 -Djib.httpTimeout=120000 -Djib.console=plain --stacktrace
        working-directory: smoke-tests/springboot