name: Build pull request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  assemble:
    uses: ./.github/workflows/reusable-assemble.yml
    with:
      cache-read-only: true

  test-java11:
    uses: ./.github/workflows/reusable-test-11.yml
    with:
      cache-read-only: true

  # this is not a required check to avoid blocking pull requests if new misspellings are added
  # to the misspell dictionary
  misspell-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: ${{ !startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/reusable-misspell-check.yml

  required-status-check:
    needs:
      - assemble
      - test-java11
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.assemble.result != 'success' ||
          needs.test-java11.result != 'success'
        run: exit 1