name: Build Play smoke test distribution

on:
  push:
    paths:
      - 'smoke-tests/play/**'
      - '.github/workflows/build-play-smoke-dist.yaml'
    branches: 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.3
        with:
          job-id: play-smoke

      - name: Login to GitHub Package Registry
        run: docker login -u ${{ secrets.BINTRAY_USER }} -p ${{ secrets.BINTRAY_API_KEY }} open-telemetry-docker-dev.bintray.io

      - name: Build Docker Image
        run: |
          ./gradlew jib -PtargetJDK=8 -Djib.httpTimeout=120000 -Djib.console=plain
          ./gradlew jib -PtargetJDK=11 -Djib.httpTimeout=120000 -Djib.console=plain
          ./gradlew jib -PtargetJDK=14 -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: smoke-tests/play