name: GraalVM native tests

on:
  schedule:
    # daily at 4:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  graalvm-native-tests:
    uses: ./.github/workflows/reusable-native-tests

  workflow-notification:
    needs:
      - graalvm-native-tests
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.build.result == 'success' }}
