name: Overhead benchmark (daily)
on:
  schedule:
    # daily at 5:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-overhead-tests:
    permissions:
      contents: write # for git push to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: gh-pages
          path: gh-pages

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/benchmark-overhead/results/ benchmark-overhead/results/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

      - name: Run tests
        working-directory: benchmark-overhead
        run: ./gradlew test

      - name: Inspect the results dir
        working-directory: benchmark-overhead
        run: ls -lR results

      - name: Copy results back to gh-pages branch
        run: rsync -avv benchmark-overhead/results/ gh-pages/benchmark-overhead/results/ && rm -rf benchmark-overhead/results

      - name: Use CLA approved bot
        run: .github/scripts/use-cla-approved-bot.sh

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: Commit updated results
        env:
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
        working-directory: ./gh-pages
        run: |
          git add benchmark-overhead/results
          git commit -m "update test result data"
          git push

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - run-overhead-tests
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.run-overhead-tests.result == 'success' }}
