name: Overhead benchmark (daily)
on:
  schedule:
    # daily at 5:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-overhead-tests:
    permissions:
      contents: write # for git push to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: gh-pages
          path: gh-pages

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/benchmark-overhead/results/ benchmark-overhead/results/

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build Latest Snapshot JAR
        run: ./gradlew assemble -x javadoc

      - name: Run tests
        working-directory: benchmark-overhead
        run: ./gradlew test

      - name: Inspect the results dir
        working-directory: benchmark-overhead
        run: ls -lR results

      - name: Copy results back to gh-pages branch
        run: rsync -avv benchmark-overhead/results/ gh-pages/benchmark-overhead/results/ && rm -rf benchmark-overhead/results

      - name: Use CLA approved bot
        working-directory: ./gh-pages
        run: ../.github/scripts/use-cla-approved-bot.sh

      - name: Commit updated results
        working-directory: ./gh-pages
        run: |
          git add benchmark-overhead/results
          git commit -m "update test result data"
          git push

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - run-overhead-tests
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.run-overhead-tests.result == 'success' }}
