name: PR build Servlet images for smoke tests

on:
  pull_request:
    paths:
      - 'smoke-tests/images/servlet/**'
      - '.github/workflows/pr-smoke-test-servlet-images.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        smoke-test-server:
          - jetty
          - liberty
          - payara
          - tomcat
          - tomee
          - websphere
          - wildfly
        exclude:
          - os: windows-latest
            smoke-test-server: websphere
      fail-fast: false
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Build Linux docker images
        if: matrix.os != 'windows-latest'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildLinuxTestImages -PsmokeTestServer=${{ matrix.smoke-test-server }}
          build-root-directory: smoke-tests/images/servlet
          cache-read-only: true

      - name: Build Windows docker images
        if: matrix.os == 'windows-latest'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildWindowsTestImages -PsmokeTestServer=${{ matrix.smoke-test-server }}
          build-root-directory: smoke-tests/images/servlet
          cache-read-only: true
