name: PR build Play images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/play/**"
      - ".github/workflows/pr-smoke-test-play-images.yml"
      - ".github/workflows/reusable-smoke-test-images.yml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:play"
      cache-read-only: true
      # Play doesn't support Java 16+ yet
      # https://github.com/playframework/playframework/pull/10819
      skip-java-17: true
      skip-java-21: true
