name: PR build Quarkus images for smoke tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-pr-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:quarkus"
      cache-read-only: true
      # Quarkus 3.7+ requires Java 17+
      skip-java-8: true
      skip-java-11: true
