# dummy comment to trigger workflow
name: PR build Quarkus images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/quarkus/**"
      - ".github/workflows/pr-smoke-test-quarkus-images.yml"
      - ".github/workflows/reusable-smoke-test-images.yml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:quarkus"
      cache-read-only: true
      # Quarkus 3.7+ requires Java 17+
      skip-java-8: true
      skip-java-11: true
