name: PR build Spring Boot images for smoke tests

on:
  pull_request:
    paths:
      - 'smoke-tests/images/spring-boot/**'
      - '.github/workflows/pr-smoke-test-spring-boot-images.yml'

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: :smoke-tests:images:spring-boot
      cache-read-only: true
