name: PR build Play images for smoke tests

on:
  pull_request:
    paths:
      - 'smoke-tests/images/play/**'
      - '.github/workflows/pr-smoke-test-play-images.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Build Java 8 Docker Image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jibDockerBuild -PtargetJDK=8 -Djib.httpTimeout=120000 -Djib.console=plain
          build-root-directory: smoke-tests/images/play
          cache-read-only: true

      - name: Build Java 11 Docker Image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jibDockerBuild -PtargetJDK=11 -Djib.httpTimeout=120000 -Djib.console=plain
          build-root-directory: smoke-tests/images/play
          cache-read-only: true

        # Play doesn't support Java 16 (or 17) yet
        # https://github.com/playframework/playframework/pull/10819
      - name: Build Java 15 Docker Image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jibDockerBuild -PtargetJDK=15 -Djib.httpTimeout=120000 -Djib.console=plain
          build-root-directory: smoke-tests/images/play
          cache-read-only: true
