name: PR build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 15]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }} for running tests
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set JDK ${{ matrix.java }} home
        run: echo "::set-env name=JAVA_${{ matrix.java }}_HOME::${{ env.JAVA_HOME }}"

      - name: Set up JDK 11 for running Gradle
        if: matrix.java != 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk${{ matrix.java }}
          arguments: testJava${{ matrix.java }} --stacktrace

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / jdk${{matrix.java}}"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

  muzzle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        uses: burrunan/gradle-cache-action@v1.4
        with:
          job-id: muzzle
          arguments: muzzle
