name: PR build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running checks
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore cache
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk11

      - name: Build
        uses: nick-invision/retry@v1
        with:
          command: ./gradlew check --stacktrace -x :smoke-tests:test
          timeout_minutes: 90
          max_attempts: 3

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / jdk11"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 15 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - id: setup-test-java
        name: Set up JDK ${{ matrix.java }} for running tests
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore cache
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk${{ matrix.java }}

      - name: Test
        uses: nick-invision/retry@v1
        with:
          command: ./gradlew testJava${{ matrix.java }} --stacktrace -x :smoke-tests:test -Dorg.gradle.java.installations.paths=${{ steps.setup-test-java.outputs.path }}
          timeout_minutes: 90
          max_attempts: 3

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / jdk${{matrix.java}}"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore cache
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: smokeTests

      - name: Test
        uses: nick-invision/retry@v1
        with:
          command: ./gradlew :smoke-tests:test
          timeout_minutes: 90
          max_attempts: 3

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / smoke"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

  setup-muzzle-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"module\":[\"$(./gradlew -q instrumentation:listInstrumentations | xargs echo | sed 's/ /","/g')\"]}"

  muzzle:
    needs: setup-muzzle-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup-muzzle-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run  muzzle
        run: ./gradlew ${{ matrix.module }}:muzzle --no-daemon

  accept-pr:
    needs: [ build, test, smoke-test, muzzle ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      # run this action to get workflow conclusion
      # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Fail build
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
        run: exit 1