name: PR build

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 15 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }} for running tests
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set JDK ${{ matrix.java }} home
        run: echo "::set-env name=JAVA_${{ matrix.java }}_HOME::${{ env.JAVA_HOME }}"

      - name: Set up JDK 11 for running Gradle
        if: matrix.java != 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Debug space
        run: df -h

      - name: Test
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk${{ matrix.java }}
          arguments: testJava${{ matrix.java }} --stacktrace -x :smoke-tests:test

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / jdk${{matrix.java}}"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Debug space
        run: df -h

      - name: Test
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk11
          arguments: :smoke-tests:test

      - name: Debug space
        if: always()
        run: df -h

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / smoke"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"

#  setup-muzzle-matrix:
#    runs-on: ubuntu-latest
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2
#      - name: Set up JDK 11 for running Gradle
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - id: set-matrix
#        run: echo "::set-output name=matrix::{\"module\":[\"$(./gradlew -q instrumentation:listInstrumentations | xargs echo | sed 's/ /","/g')\"]}"
#
#  muzzle:
#    needs: setup-muzzle-matrix
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{fromJson(needs.setup-muzzle-matrix.outputs.matrix)}}
#      fail-fast: false
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2
#      - name: Set up JDK 11 for running Gradle
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Run  muzzle
#        run: ./gradlew ${{ matrix.module }}:muzzle --no-daemon
#
#  accept-pr:
#    needs: [ test, smoke-test, muzzle ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Success
#        run: echo Build successful