name: Publish Quarkus images for smoke tests

on:
  push:
    paths:
      - 'smoke-tests/images/quarkus/**'
      - '.github/workflows/publish-smoke-test-quarkus-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      build-root-directory: smoke-tests/images/quarkus
      publish: true
      # Quarkus 2.0+ does not support Java 8
      skip-java-8: true

  issue:
    name: Open issue on failure
    needs: publish
    runs-on: ubuntu-latest
    if: always()
    steps:
      # run this action to get workflow conclusion
      # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v2.2

      - uses: actions/checkout@v3

      - uses: JasonEtco/create-an-issue@v2.6
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/workflow-failed.md
