name: Publish Spring Boot images for smoke tests

on:
  push:
    paths:
      - 'smoke-tests/images/spring-boot/**'
      - '.github/workflows/publish-smoke-test-spring-boot-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      build-root-directory: smoke-tests/images/spring-boot
      publish: true

  issue:
    name: Open issue on failure
    needs: publish
    if: failure()
    uses: ./.github/workflows/reusable-create-issue-for-failure.yml
