name: Publish Servlet images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/servlet/**"
      - ".github/workflows/publish-smoke-test-servlet-images.yml"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - id: set-tag
        name: Set tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

  publish:
    permissions:
      contents: read
      packages: write
    needs: prepare
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # this is needed for TAG construction below on Windows
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        smoke-test-server:
          - jetty
          - liberty
          - payara
          - tomcat
          - tomee
          - websphere
          - wildfly
        exclude:
          - os: windows-latest
            smoke-test-server: websphere
      fail-fast: false
    steps:
      - name: Support long paths
        run: git config --system core.longpaths true
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Free disk space
        if: matrix.os != 'windows-latest'
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Login to GitHub package registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          # only push cache for one matrix option per OS since github action cache space is limited
          cache-read-only: ${{ matrix.smoke-test-suite != 'tomcat' }}

      - name: Build Linux docker images
        if: matrix.os != 'windows-latest'
        run: ./gradlew :smoke-tests:images:servlet:buildLinuxTestImages pushMatrix -PextraTag=${{ needs.prepare.outputs.tag }} -PsmokeTestServer=${{ matrix.smoke-test-server }}

      - name: Build Windows docker images
        if: matrix.os == 'windows-latest'
        run: ./gradlew :smoke-tests:images:servlet:buildWindowsTestImages pushMatrix -PextraTag=${{ needs.prepare.outputs.tag }} -PsmokeTestServer=${{ matrix.smoke-test-server }}

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - publish
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
