name: Publish Play images for smoke tests

on:
  push:
    paths:
      - 'smoke-tests/images/play/**'
      - '.github/workflows/publish-smoke-test-play-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      build-root-directory: smoke-tests/images/play
      publish: true
      # Play doesn't support Java 16+ yet
      # https://github.com/playframework/playframework/pull/10819
      skip-java-17: true
      skip-java-18: true

  publish-java-15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2

        # Play doesn't support Java 16 (or 17) yet
        # https://github.com/playframework/playframework/pull/10819
      - name: Build Java 15 Docker Image
        run: ./gradlew jib -PtargetJDK=15 -Djib.httpTimeout=120000 -Djib.console=plain -Ptag=${{ env.TAG }}
        working-directory: smoke-tests/images/play

  issue:
    name: Open issue on failure
    needs: [ publish, publish-java-15 ]
    if: failure()
    uses: ./.github/workflows/reusable-create-issue-for-failure.yml
