name: Reusable - Muzzle

on:
  workflow_call:
    inputs:
      cache-read-only:
        type: boolean
        required: false

permissions:
  contents: read

jobs:
  muzzle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ":instrumentation:muzzle1"
          - ":instrumentation:muzzle2"
          - ":instrumentation:muzzle3"
          - ":instrumentation:muzzle4"
      fail-fast: false
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d9336dac04dea2507a617466bc058a3def92b18b # v3.4.0
        with:
          cache-read-only: ${{ inputs.cache-read-only }}

      - name: Run muzzle
        run: ./gradlew ${{ matrix.task }}
